### ISSUE TITLE
macOS: runs into an error

### ISSUE THREAD

**Issue by ufkel** [dburr/scsi2sd_to_hda#1]
Thank you for this great script. 
However, on macOS it runs into an error:

> $ dd if=SCSI2SDv51-backup.img of=HD00_512.hda bs=512 skip=0 count=2097152
> 2097152+0 records in
> 2097152+0 records out
> 1073741824 bytes transferred in 7.839232 secs (136970283 bytes/sec)
> file should be 1073741824 in size
> stat: illegal option -- c
> usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file ...]
> ./scsi2sd_to_hda.sh: line 125: [: -eq: unary operator expected

Line 125: The "stat" command needs a different parameter. On macOS it is "stat -f%z" instead of "stat -c%s"

Just a small remark, in case somebody else runs into the same problem

**Comment by dburr** [comment]
Should be fixed now. You will need to install the "coreutils" package from Homebrew to get the GNU variant of "stat." Follow the instructions at https://brew.sh/ then install coreutils by typing `brew install coreutils`. Note that this will install it as "gstat" so as not to conflict with the "stat" that came with OS X (so that it won't break any existing scripts that might be using it.)

**Comment by dburr** [comment]
Err... ok, I should really read issues before jumping into fixing code. My mind instantly jumped to "oh, I need the gnu variant of stat" and I completely overlooked the fact that "stat -f%z" would have worked. 🤦‍♂️ If you'd rather I rewrite my "fix" to use OS X's built in "stat" please let me know.
